Repository hapijs/nes, pull requests merged in 2018-03, with the labels that each got.

#220 Ignore node network errors after opening client socket
  dist/client.js
  lib/client.js
  test/client.js
  test/socket.js
Labels: bug

#222 Allow isSameSite cookie option to be passed
  lib/index.js
Labels: enhancement

#223 Delay heartbeats until server is started
  lib/index.js
  lib/listener.js
Labels: bug

#224 Add socket.info object
  lib/socket.js
  test/socket.js
Labels: enhancement

#226 Fix broken links in API.md
  API.md
Labels: documentation

#228 Mark NesErrors as coming from nes
  dist/client.js
  lib/client.js
  test/client.js
Labels: enhancement

#229 Update ws to 5.x.x
  dist/client.js
  lib/client.js
  package.json
  test/client.js
Labels: breaking changes, dependency
