Repository hapijs/nes, pull requests merged in 2018-11, with the labels that each got.

#234 Lock in empty response behavior
  test/client.js
Labels: test

#259 Add node 11 to travis again
  .travis.yml
Labels: bug

#262 Close the socket when authentication verification fails
  API.md
  PROTOCOL.md
  README.md
  dist/client.js
  lib/client.js
  lib/index.js
  lib/listener.js
  lib/socket.js
  test/auth.js
  test/client.js
Labels: enhancement

#264 Add changelog.md
  CHANGELOG.md
Labels: documentation
